# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: graph_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'graph_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13graph_service.proto\x12\x1cgraphmind.grpc.graph_service\"\x92\x01\n\x0c\x42uildRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x10\n\x08taskName\x18\x02 \x01(\t\x12\x36\n\x06status\x18\x03 \x01(\x0e\x32&.graphmind.grpc.graph_service.StatusId\x12\x18\n\x0b\x62oltAddress\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_boltAddress\"x\n\x0b\x42uildStatus\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x10\n\x08taskName\x18\x02 \x01(\t\x12\x36\n\x06status\x18\x03 \x01(\x0e\x32&.graphmind.grpc.graph_service.StatusId\x12\x0f\n\x07message\x18\x04 \x01(\t*\x98\x01\n\x08StatusId\x12\r\n\tUNPROCESS\x10\x00\x12\x0e\n\nPROCESSING\x10\x01\x12\r\n\tPROCESSED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x12\x0b\n\x07TIMEOUT\x10\x04\x12\r\n\tCANCELLED\x10\x05\x12\t\n\x05READY\x10\n\x12\t\n\x05START\x10\x0b\x12\t\n\x05PAUSE\x10\x0c\x12\x0c\n\x08\x43ONTINUE\x10\r\x12\x07\n\x03\x45ND\x10\x0e\x32p\n\x0cGraphService\x12`\n\x05\x62uild\x12*.graphmind.grpc.graph_service.BuildRequest\x1a).graphmind.grpc.graph_service.BuildStatus\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSID']._serialized_start=325
  _globals['_STATUSID']._serialized_end=477
  _globals['_BUILDREQUEST']._serialized_start=54
  _globals['_BUILDREQUEST']._serialized_end=200
  _globals['_BUILDSTATUS']._serialized_start=202
  _globals['_BUILDSTATUS']._serialized_end=322
  _globals['_GRAPHSERVICE']._serialized_start=479
  _globals['_GRAPHSERVICE']._serialized_end=591
# @@protoc_insertion_point(module_scope)
